### ISSUE TITLE
Hover text should be richer thanks to popover

### ISSUE THREAD

**Issue by lenybernard** [FriendsOfVictoire/WidgetImageBundle#5]
By adding a hoverType select with choices('normal', "popover'), it could be more flexible :
![edition - image b](https://cloud.githubusercontent.com/assets/618536/9441534/04dda3ae-4a77-11e5-94cf-0287ae274a98.jpg)
(sorry for french in pitcture)

**Comment by talbotseb** [comment]
@lenybernard : this issue is now longer needed
